<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIH-D-16328" ignored="0" name="_设备1_" tests="5" failures="1" timestamp="24 十二月 2018 09:38:18 GMT" time="282.37" errors="0">
  <testcase name="runCase" time="56.525" classname="com.netease.qa.ai.smartauto.runners.Runner0"/>
  <testcase name="runCase" time="56.116" classname="com.netease.qa.ai.smartauto.runners.Runner1"/>
  <testcase name="runCase" time="48.931" classname="com.netease.qa.ai.smartauto.runners.Runner2"/>
  <testcase name="runCase" time="91.557" classname="com.netease.qa.ai.smartauto.runners.Runner3"/>
  <testcase name="runCase" time="29.196" classname="com.netease.qa.ai.smartauto.runners.Runner4">
    <failure type="java.lang.AssertionError" message="执行失败或程序异常：点击工作台。截图及报告：http://smartauto.hz.netease.com/report/casereport?case_id=72591&amp;amp;device_id=3684">
      <![CDATA[java.lang.AssertionError: 执行失败或程序异常：点击工作台。截图及报告：http://smartauto.hz.netease.com/report/casereport?case_id=72591&device_id=3684
at com.netease.qa.ai.smartauto.runners.Runner4.runCase(Runner4.java:31)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- runCase -->
</testsuite> <!-- _设备1_ -->
