<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIH-D-16328" ignored="0" name="_设备1_" tests="12" failures="2" timestamp="25 十二月 2018 06:52:53 GMT" time="687.574" errors="0">
  <testcase name="runCase" time="48.326" classname="com.netease.qa.ai.smartauto.runners.Runner0"/>
  <testcase name="runCase" time="35.762" classname="com.netease.qa.ai.smartauto.runners.Runner1">
    <failure type="java.lang.AssertionError" message="执行失败或程序异常：上滑直至出现保存题目。截图及报告：http://smartauto.hz.netease.com/report/casereport?case_id=73852&amp;amp;device_id=3755">
      <![CDATA[java.lang.AssertionError: 执行失败或程序异常：上滑直至出现保存题目。截图及报告：http://smartauto.hz.netease.com/report/casereport?case_id=73852&device_id=3755
at com.netease.qa.ai.smartauto.runners.Runner1.runCase(Runner1.java:31)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- runCase -->
  <testcase name="runCase" time="39.838" classname="com.netease.qa.ai.smartauto.runners.Runner2"/>
  <testcase name="runCase" time="40.042" classname="com.netease.qa.ai.smartauto.runners.Runner3">
    <failure type="java.lang.AssertionError" message="执行失败或程序异常：点击保存。截图及报告：http://smartauto.hz.netease.com/report/casereport?case_id=73857&amp;amp;device_id=3755">
      <![CDATA[java.lang.AssertionError: 执行失败或程序异常：点击保存。截图及报告：http://smartauto.hz.netease.com/report/casereport?case_id=73857&device_id=3755
at com.netease.qa.ai.smartauto.runners.Runner3.runCase(Runner3.java:31)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- runCase -->
  <testcase name="runCase" time="80.511" classname="com.netease.qa.ai.smartauto.runners.Runner4"/>
  <testcase name="runCase" time="46.974" classname="com.netease.qa.ai.smartauto.runners.Runner5"/>
  <testcase name="runCase" time="77.546" classname="com.netease.qa.ai.smartauto.runners.Runner6"/>
  <testcase name="runCase" time="48.96" classname="com.netease.qa.ai.smartauto.runners.Runner7"/>
  <testcase name="runCase" time="87.838" classname="com.netease.qa.ai.smartauto.runners.Runner8"/>
  <testcase name="runCase" time="50.819" classname="com.netease.qa.ai.smartauto.runners.Runner9"/>
  <testcase name="runCase" time="105.416" classname="com.netease.qa.ai.smartauto.runners.Runner10"/>
  <testcase name="runCase" time="25.439" classname="com.netease.qa.ai.smartauto.runners.Runner11"/>
</testsuite> <!-- _设备1_ -->
